name: Build
on: [push, pull_request]
jobs:
  build:
    needs: [ xml-lint ]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - name: Convert to JSON
        run: ./bin/convertXmlToJson.php list.xml list.json
  xml-lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: lint
        run: xmllint --xinclude --noout --schema volkswaigen.xsd list.xml || exit 1

